const TYPES = {
  //app
  SET_BOARD: "SET_BOARD",
  SET_SELECTED: "SET_SELECTED",
  SWITCH_PLAYER: "SWITCH_PLAYER",
  SET_PLAYER: "SET_PLAYER",
  SET_PAWN_TO_CHANGE: "SET_PAWN_TO_CHANGE",
  //config
  SET_MODEL_SWITCH_PAWN_OPEN: "SET_MODEL_SWITCH_PAWN_OPEN",
};

export default TYPES;
